<!DOCTYPE html>
<html lang="hu">
	<head>
		<meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
		<title>PC Wallpaper 2</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
		<link rel="stylesheet" href="style.css">		
	</head>
	<body>
        <div class="container-fluid"> 
            <div id="wallpaper">SGN Wallpaper..... Ez az információ csak mobiltelefonon jelenik meg!</div>
            <div class="row">
                <?php foreach ($params['cikk'] as $c) : ?>
                    <h3 class="center" id=<?=$c["id"]?>><?=$c["cim"]?></h3>
                    <p><?=$c["cikk"]?></p>
                    <p><strong><?=$c["eredmeny"]?></strong></p>
                    <p><?=$c["csapattagok"]?></p>
                    <p><?=$c["edzoinyilatkozat"]?></p>

                    <?php if ($c['kepek'] != "0") : ?>
                        <?php if ($c['kepek'] == "1") : ?>
                        <div class='row'>
                            <div class='col-md-3'></div>
                                <div class='col-md-6'>
                                    <div class='thumbnail'>
                                        <a href="./public/kepek/<?= $params['oldalKephez'] ?><?=$c['id']?>1.jpg" target='blank'>
                                            <img src="./public/kepek/<?= $params['oldalKephez'] ?><?=$c['id']?>1.jpg" alt='Játék' style='width:100%'>
                                            <div class='caption'><p></p></div>
                                        </a>
                                    </div>
                                </div>
                            <div class='col-md-3'></div>
                        </div>
                        <?php else :?>
                            <?php $j = $c['kepek'];
                                for ($i = 0; $i < $j-1; $i=$i+2) :?>
                                    <div class='row'>
                                        <div class='col-md-6'>
                                            <div class='thumbnail'>
                                                <a href="./public/kepek/<?= $params['oldalKephez'] ?><?=$c['id'].($i+1)?>.jpg" target='_blank'>
                                                    <img src="./public/kepek/<?= $params['oldalKephez'] ?><?=$c['id'].($i+1)?>.jpg" alt='Játék' style='width:100%'>
                                                    <div class='caption'><p></p></div>
                                                </a>
                                            </div>
                                        </div>
                                        <div class='col-md-6'>
                                            <div class='thumbnail'>
                                                <a href="./public/kepek/<?= $params['oldalKephez'] ?><?=$c['id'].($i+2)?>.jpg" target='_blank'>
                                                    <img src="./public/kepek/<?= $params['oldalKephez'] ?><?=$c['id'].($i+2)?>.jpg" alt='Játék' style='width:100%'>
                                                    <div class='caption'><p></p></div>
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                <?php endfor; ?>
                        <?php endif; ?>
                    <?php endif; ?>
                <?php endforeach;?>

                <div class="mySlides">
                    <img class="mx-auto d-block" src="kepek/sgn1.jpg" alt="N" style="width:85%">
                </div>
                <div class="mySlides">
                    <img class="mx-auto d-block" src="kepek/sgn2.jpg" alt="N" style="width:85%">
                </div>
                <!-- <div class="mySlides">
                    <div class="display1">
                        <h1 id="name1"></h1>
                        <p>Hőmérséklet:</p>
                        <p id="temp1"></p>
                        <p id="desc1"></p>
                    </div>
                </div> -->
                <div class="mySlides">
                    <img class="mx-auto d-block" src="kepek/sgn3.jpg" alt="N" style="width:85%">
                </div>
                <div class="mySlides">
                    <img class="mx-auto d-block" src="kepek/sgn4.jpg" alt="N" style="width:85%">
                </div>
                <!-- <div class="mySlides">
                    <div class="display2">
                        <h1 id="name2"></h1>
                        <p>Hőmérséklet:</p>
                        <p id="temp2"></p>
                        <p id="desc2"></p>
                    </div>
                </div> -->
                <div id="onlyTime">
                    <div class="mySlides">
                        <div id="clock3"></div>
                    </div>
                </div>
                <!-- <div id="onlyTime">
                    <div id="clock3"></div>
                </div> -->
            </div> 
        </div>
	</body>
    <script src="script.js"></script>
</html>